name: build_and_test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04]
        compiler: [g++-12, clang++-14]
        cpp_standard: [20]
        build_type: [Debug, Release]
    name: WF ${{matrix.os}} ${{matrix.build_type}} ${{matrix.compiler}}-${{matrix.cpp_standard}}
    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install ninja-build lld gcc-12 clang-14
          sudo ln -sf /usr/local/bin/ld /usr/bin/lld
      - name: Configure CMake
        run: |
          cmake . -DCLINOK_ENABLE_TESTING=ON              \
            -DCMAKE_BUILD_TYPE=${{matrix.build_type}} \
            -DCMAKE_CXX_COMPILER=${{matrix.compiler}} \
            -DCMAKE_CXX_STANDARD=${{matrix.cpp_standard}}   \
            -B build -G "Ninja"
      - name: Build
        run:
          cmake --build build

      - name: Test
        run: |
          cd build
          ctest --output-on-failure -C ${{matrix.build_type}} -V
      - name: Configure CMake (sanitizers)
        run: |
          cmake . -DCLINOK_ENABLE_TESTING=ON              \
            -DCMAKE_BUILD_TYPE=${{matrix.build_type}} \
            -DCMAKE_CXX_COMPILER=${{matrix.compiler}} \
            -DCMAKE_CXX_STANDARD=${{matrix.cpp_standard}}   \
            -B build_sanitizers -G "Ninja" -DCLINOK_SANITIZE=ON
      - name: Build (sanitizers)
        run:
          cmake --build build_sanitizers

      - name: Test (sanitizers)
        run: |
          cd build_sanitizers
          ctest --output-on-failure -C ${{matrix.build_type}} -V
